apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: w6b1jr22d-python 
  janus-idp.io/tekton: w6b1jr22d-python
  backstage.io/kubernetes-id: w6b1jr22d-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: w6b1jr22d-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml